version: '3.4'
services:
  trustlines-monitor.dnp.dappnode.eth:
    image: 'trustlines-monitor.dnp.dappnode.eth:0.1.0'
    build: ./build
    volumes:
      - 'trustlines_shared:/config'
      - 'state:/state'
      - 'reports:/reports'
    restart: on-failure
volumes:
  state: {}
  reports: {}
  trustlines_shared:
    external: true
